# Generated by Django 4.0.3 on 2022-11-15 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='tarih',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
