# Generated by Django 4.0.3 on 2022-11-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_urun_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='tarih',
            field=models.DateField(auto_now_add=True),
        ),
    ]
