# Generated by Django 4.0.3 on 2022-11-17 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_alter_urun_tarih'),
    ]

    operations = [
        migrations.CreateModel(
            name='Not',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('konu', models.TextField()),
                ('tarih', models.DateField(auto_now_add=True)),
                ('fidelik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.fidelik')),
            ],
        ),
    ]
