# Generated by Django 4.0.3 on 2022-11-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_notification_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='tarih',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
