# Generated by Django 4.0.3 on 2022-11-28 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0006_message_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='konu',
        ),
        migrations.AddField(
            model_name='notification',
            name='fidelik',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='page.fidelik'),
        ),
        migrations.AddField(
            model_name='notification',
            name='tarih',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
