# Generated by Django 4.0.3 on 2022-12-05 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_remove_notification_konu_notification_fidelik_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(choices=[('Ayrıkmak Yedek Parçaları', 'Ayrıkmak Yedek Parçaları'), ('İthal Markalar Yedek Parçaları', 'İthal Markalar Yedek Parçaları'), ('Ayrıkmak Makinalar', 'Ayrıkmak Makinalar')], max_length=200),
        ),
        migrations.DeleteModel(
            name='Kategori',
        ),
    ]
