# Generated by Django 4.0.3 on 2022-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_alter_urun_tarih'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urun',
            name='dolar',
        ),
        migrations.RemoveField(
            model_name='urun',
            name='tl',
        ),
        migrations.AddField(
            model_name='urun',
            name='cins',
            field=models.CharField(choices=[('dolar', '$'), ('tl', '₺')], max_length=200, null=True),
        ),
    ]
