# Generated by Django 4.0.3 on 2022-12-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_remove_urun_dolar_remove_urun_tl_urun_cins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fidelik',
            name='adres',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fidelik',
            name='isim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fidelik',
            name='mail',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='fidelik',
            name='mak_sayisi',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='fidelik',
            name='tel',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='fidelik',
            name='yetkili',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='fiyat',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='isim',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='urun',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Ayrıkmak Yedek Parçaları', 'Ayrıkmak Yedek Parçaları'), ('İthal Markalar Yedek Parçaları', 'İthal Markalar Yedek Parçaları'), ('Ayrıkmak Makinalar', 'Ayrıkmak Makinalar')], max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
